api/urls.py
from django.urls import path

from api.views import apiDestinations, apiOverview, days

app_name = 'api'

urlpatterns = [
    path('', apiOverview, name='overview'),
    path('destinations/<str:pk>', apiDestinations, name='destinations'),
    path('days/<str:pk>', days, name='days'),
]

contacts/urls.py
from django.urls import path

from contacts.views import BookingView, CarHireView, SuccessView, TentHireView, sendMail
app_name = 'contacts'

urlpatterns = [
    path('sendmail/', sendMail, name='send_mail'),
    path('booking/', BookingView.as_view(), name='book_now'),
    path('booking/success/', SuccessView.as_view(), name='success'),
    path('forms/tents/', TentHireView.as_view(), name='tent-hire'),
    path('forms/cars/', CarHireView.as_view(), name='car-hire'),
]

kaizen/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf.urls import handler500

handler500 = 'main.views.server_error500'
handler404 = 'main.views.error404View'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls", namespace='main')),
    path('destinations/', include("destinations.urls", namespace='destinations')),
    path('api/', include("api.urls", namespace='api')),
    path('contact/', include("contacts.urls", namespace='contacts')),
]

# handling the 404 error


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.views import HomeView, HoneymoonView, bookingView, equipmentView, galleryView

app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name='home-view'),
    path('equipment/', equipmentView, name='equipment-view'),
    path('gallery/', galleryView, name='gallery-view'),
    path('booking/', bookingView, name='booking-view'),
    path('spots/', HoneymoonView.as_view(), name='honeymoon-list'),
    path('spots/<int:pk>/', HoneymoonView.as_view(), name='honeymoon-detail'),
]

contacts/models.py
from django.db import models

# Create your models here.
class Receipient(models.Model):
    email = models.EmailField()

    class Meta:
        verbose_name = 'Receipient'
        verbose_name_plural = 'Email Receipients'

    def __str__(self):
        return self.email

contacts/forms.py
# from main.models import Subscriber
from django import forms
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.conf import settings

from contacts.models import Receipient


# class NewsletterForm(forms.ModelForm):
#     class Meta:
#         model = Subscriber
#         fields = (
#             'email',
#         )

class ContactForm(forms.Form):
    your_name = forms.CharField(required=False)
    your_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    your_message = forms.CharField(widget=forms.Textarea, required=True)
    # message = forms.CharField(widget=forms.Textarea, required=True)

    def send_email(self, subject, email, text, name):
        subject = subject
        email = email
        text = text
        name = name
        message = f"{name}: {email}\n\n{text}"

        try:
            send_mail(subject, message, settings.EMAIL_HOST_USER, ['amartislab@gmail.com','elijahtriumph@amartislab.com','support@amartislab.com'], fail_silently=False)
        except BadHeaderError:
            return HttpResponse('Invalid header found.')

CONTACT_CHOICES = [
    ('Email', 'Email'),
    ('Phone', 'Phone'),
    ('Either', 'Either'),
]

TIME_CHOICES = [
    ('8AM - 11AM', '8AM - 4AM'),
    ('12PM - 4PM', '12PM - 4PM'),
    ('5PM - 10PM', '5PM - 10PM'),
]

SLEEPER_CHOICES = [
    ('1-2 Sleeper', '1-2 Sleeper'),
    ('3-4 Sleeper', '3-4 Sleeper'),
]

CAR_CHOICES = [
    ('7-8 seater', '7-8 seater'),
    ('4 seater', '4 seater'),
    ('6 seater', '6 seater'),
]

class BookingForm(forms.Form):
    first_name = forms.CharField(label='First Name', required=True)
    last_name = forms.CharField(label='Last Name', required=True)
    email = forms.EmailField(label='Email', required=True)
    phone = forms.CharField(label='Phone Number', max_length=15, required=False)
    visit_date = forms.DateField(label='When are you planning to visit?', widget=forms.SelectDateWidget)
    no = forms.IntegerField(label='How many are you?', required=False)
    group_no = forms.IntegerField(label='If a group, How many People are in the group?', required=False)
    tour = forms.CharField(label='Which Tour or Visit are you intrested in?', required=False)
    contact_choice = forms.ChoiceField(label="What's the best way to contact you?", choices=CONTACT_CHOICES, widget=forms.RadioSelect, required=False)
    time_choice = forms.ChoiceField(label='If phone what is the best time to call you? (EAT)', choices=TIME_CHOICES, widget=forms.RadioSelect, required=False)
    more_info = forms.CharField(label='Anything Else we should know', widget=forms.Textarea, required=False)

    def send_mail(self):
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        email = self.cleaned_data.get('email')
        phone = self.cleaned_data.get('phone')
        visit_date = self.cleaned_data.get('visit_date')
        no = self.cleaned_data.get('no')
        group_no = self.cleaned_data.get('group_no')
        tour = self.cleaned_data.get('tour')
        contact_choice = self.cleaned_data.get('contact_choice')
        time_choice = self.cleaned_data.get('time_choice')
        more_info = self.cleaned_data.get('more_info')

        try:
            message = f'Name: {first_name} {last_name}\nEmail: {email}\nPhone: {phone}\nWhen they want to visit: {visit_date}\nNumber of people: {no}\nNumber in group: {group_no}\nTour interested in: {tour}\nPrefered contact method: {contact_choice}\nPrefered time of contact: {time_choice}\nMore information: {more_info}'
            subject = 'Booking'
            send_mail(subject, message, settings.EMAIL_HOST_USER, [r.email for r in Receipient.objects.all()], fail_silently=False)
            # print(message)
        except BadHeaderError:
            return HttpResponse('Invalid header found.')


class TentHireForm(forms.Form):
    first_name = forms.CharField(label='First Name', required=True)
    last_name = forms.CharField(label='Last Name', required=True)
    email = forms.EmailField(label='Email', required=True)
    phone = forms.CharField(label='Phone Number', max_length=15, required=True)
    sleepers = forms.ChoiceField(label="Tent type", choices=SLEEPER_CHOICES, widget=forms.RadioSelect, required=False)
    contact_choice = forms.ChoiceField(label="What's the best way to contact you?", choices=CONTACT_CHOICES, widget=forms.RadioSelect, required=False)
    time_choice = forms.ChoiceField(label='If phone what is the best time to call you? (EAT)', choices=TIME_CHOICES, widget=forms.RadioSelect, required=False)
    more_info = forms.CharField(label='Anything Else we should know', widget=forms.Textarea, required=False)

    def send_mail(self):
        print('sending')
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        email = self.cleaned_data.get('email')
        phone = self.cleaned_data.get('phone')
        tent = self.cleaned_data.get('sleepers')
        contact_choice = self.cleaned_data.get('contact_choice')
        time_choice = self.cleaned_data.get('time_choice')
        more_info = self.cleaned_data.get('more_info')

        try:
            message = f'Name: {first_name} {last_name}\nEmail: {email}\nPhone: {phone}\nAction: hire {tent} tent\n\nPrefered contact method: {contact_choice}\nPrefered time of contact: {time_choice}\nMore information: {more_info}'
            subject = 'Tent Hire'
            send_mail(subject, message, settings.EMAIL_HOST_USER, [r.email for r in Receipient.objects.all()], fail_silently=False)
            # print(message)
        except BadHeaderError:
            return HttpResponse('Invalid header found.')


class CarHireForm(forms.Form):
    first_name = forms.CharField(label='First Name', required=True)
    last_name = forms.CharField(label='Last Name', required=True)
    email = forms.EmailField(label='Email', required=True)
    phone = forms.CharField(label='Phone Number', max_length=15, required=True)
    vehicle = forms.ChoiceField(label="Number of seats of vehicle", choices=CAR_CHOICES, widget=forms.RadioSelect, required=False)
    contact_choice = forms.ChoiceField(label="What's the best way to contact you?", choices=CONTACT_CHOICES, widget=forms.RadioSelect, required=False)
    time_choice = forms.ChoiceField(label='If phone what is the best time to call you? (EAT)', choices=TIME_CHOICES, widget=forms.RadioSelect, required=False)
    more_info = forms.CharField(label='Anything Else we should know', widget=forms.Textarea, required=False)

    def send_mail(self):
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        email = self.cleaned_data.get('email')
        phone = self.cleaned_data.get('phone')
        vehicle = self.cleaned_data.get('vehicle')
        contact_choice = self.cleaned_data.get('contact_choice')
        time_choice = self.cleaned_data.get('time_choice')
        more_info = self.cleaned_data.get('more_info')

        try:
            message = f'Name: {first_name} {last_name}\nEmail: {email}\nPhone: {phone}\nAction: hire {vehicle} vehicle\n\nPrefered contact method: {contact_choice}\nPrefered time of contact: {time_choice}\nMore information: {more_info}'
            subject = 'Car Hire'
            send_mail(subject, message, settings.EMAIL_HOST_USER, [r.email for r in Receipient.objects.all()], fail_silently=False)
            # print(message)
        except BadHeaderError:
            return HttpResponse('Invalid header found.')

# class ContactForm(forms.Form):
#     your_name = forms.CharField(required=False)
#     your_email = forms.EmailField(required=True)
#     subject = forms.CharField(required=True)
#     your_message = forms.CharField(widget=forms.Textarea, required=True)
#     # message = forms.CharField(widget=forms.Textarea, required=True)

#     def send_email(self):
#         subject = self.cleaned_data.get('subject')
#         email = self.cleaned_data.get('your_email')
#         text = self.cleaned_data.get('your_message')
#         name = self.cleaned_data.get('your_name')
#         message = f"{name}: {email}\n\n{text}"
#         print(message)

#         try:
#             send_mail(subject, message, settings.EMAIL_HOST_USER, ['amartissebaggala@gmail.com','eliyang256@outlook.com', 'kayimaoscul@gmail.com', 'ogocharles231@gmail.com'], fail_silently=False)
#         except BadHeaderError:
#             return HttpResponse('Invalid header found.')

contacts/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render
from django.views.generic import TemplateView, FormView

from rest_framework.decorators import api_view
from rest_framework.response import Response

from contacts.forms import BookingForm, CarHireForm, TentHireForm
from contacts.models import Receipient


class BookingView(FormView):
   form_class = BookingForm
   success_url = '/contact/booking/success'
   template_name = 'contacts/booking.html'

   def post(self, request, *args, **kwargs):
      form_class = self.get_form_class()
      form = self.get_form(form_class)

      if form.is_valid():
         return self.form_valid(form)
      print('here2')
      return self.form_invalid(form)

   def form_valid(self, form):
      form.send_mail()
      return super(BookingView, self).form_valid(form)

   def form_invalid(self, form):
    #   form.send_mail()
      return super(BookingView, self).form_invalid(form)
   

class TentHireView(FormView):
   form_class = TentHireForm
   success_url = '/contact/booking/success'
   template_name = 'contacts/tent-hire.html'

   def post(self, request, *args, **kwargs):
      form_class = self.get_form_class()
      form = self.get_form(form_class)
      print(form)

      return self.form_valid(form) if form.is_valid() else self.form_invalid(form)

   def form_valid(self, form):
      form.send_mail()
      return super(TentHireView, self).form_valid(form)

   def form_invalid(self, form):
      print('here2')
      print('here2')
      # form.send_mail()
      return super(TentHireView, self).form_invalid(form)
   

class CarHireView(FormView):
   form_class = CarHireForm
   success_url = '/contact/booking/success'
   template_name = 'contacts/car-hire.html'

   def post(self, request, *args, **kwargs):
      form_class = self.get_form_class()
      form = self.get_form(form_class)

      print(form)

      if form.is_valid():
         return self.form_valid(form)
      print('here2')
      return self.form_invalid(form)

   def form_valid(self, form):
      form.send_mail()
      return super(CarHireView, self).form_valid(form)

   def form_invalid(self, form):
      # form.send_mail()
      return super(CarHireView, self).form_invalid(form)


@api_view(['POST'])
def sendMail(request):
   if request.method == 'POST':
      data = request.data
      print(data)
      message = f"Name: {data.get('name')}\nEmail: {data.get('email')}\nMessage: {data.get('message')}"
      message = f"Name: {data.get('name')}\nEmail: {data.get('email')}\nMessage: {data.get('message')}"
      print("\n\nmessage\n"+message)
      receipients = Receipient.objects.all()

      try:
         send_mail(
            subject='Sent from footer form',
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[receipient.email for receipient in receipients]
         )

         return Response('SUCCESS')
      except Exception as e:
         print(f'Exception: {e}')
         return Response('Failed')


# @api_view(['POST'])
# def bookNow(request):
#    message = 'Successfully sent your booking'
#    context = {
#       'message': message
#    }
#    template_name = 'contacts/status.html'
# def bookNow(request):
#    message = 'Successfully sent your booking'
#    context = {
#       'message': message
#    }
#    template_name = 'contacts/status.html'
   
#    if request.method == 'POST':
#       data = request.data
#       print(data)
#       message = f'''Name: {data.get('fname')} {data.get('lname')}
#       \nEmail: {data.get('email')} \t Phone number: {data.get('phone')}
#       \nWhen are you planning to visit: {data.get('date')}
#       \nHow many are you?: {data.get('single_number')}
#       \nIf a group, How many People are in the group?: {data.get('group_number')}
#       \nWhich Tour or Visit are you intrested in?: {data.get('tour')}
#       \nWhat's the best way to contact you?: {data.get('fav-means')}
#       \nIf phone what is the best time to call you?: {data.get('fav-time')}
#       \nAnything Else we should know: {data.get('anything_else')}
#       '''
#       print("\n\nmessage\n"+message)
#       receipients = Receipient.objects.all()

#       try:
#          send_mail(
#             subject='Booking',
#             message=message,
#             from_email=settings.EMAIL_HOST_USER,
#             recipient_list=[receipient.email for receipient in receipients]
#          )
#       try:
#          send_mail(
#             subject='Booking',
#             message=message,
#             from_email=settings.EMAIL_HOST_USER,
#             recipient_list=[receipient.email for receipient in receipients]
#          )

#       except Exception as e:
#          print(f'Exception: {e}')
#          message = "Failed, try again later"

#    return render(request, template_name, context)
#    return render(request, template_name, context)


class SuccessView(TemplateView):
   template_name = "contacts/success.html"

contacts/templates/contacts/booking.html
{% extends 'base.html' %}
{% load static %}
{% load tailwind_filters %}

{% block title %}Kaizen Safaris bookings{% endblock %}

{% block content %}
<section id="banner" class=" h-[70vh] overflow-hidden ">
    <div class="relative h-full">
        <img class="w-full h-full object-cover" src="{% static 'img/booking.webp' %}">
        <div class="cover z-10 absolute top-0 left-0 w-full h-full  bg-opacity-40">
            <div id="hero-space"></div>
            <div class="content-space">

            </div>
        </div>
    </div>
</section>

<section class="py-16 bg-blue-50">
    <h2 class="head-1"><span class="lead">Booking</span> Form</h2>
    <div class="container">
            <!-- {{ form|crispy }} -->
        <form method="post" class="booking-form grid gap-4 text-xl">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {{ form.management_form }}
            <fieldset class="grid grid-cols-2 gap-4">
                <div>
                    {{ form.first_name.errors }}
                    <label for="{{ form.first_name.id_for_label }}" class="form-label">First Name</label>
                    {{ form.first_name }}
                </div>
                <div>
                    {{ form.last_name.errors }}
                    <label for="{{ form.last_name.id_for_label }}" class="form-label">Last Name</label>
                    {{ form.last_name }}
                </div>
            </fieldset>
            <fieldset class="grid grid-cols-2 gap-4">
                <div>
                    {{ form.email.errors }}
                    <label for="{{ form.email.id_for_label }}" class="form-label">Email</label>
                    {{ form.email }}
                </div>
                <div>
                    {{ form.phone.errors }}
                    <label for="{{ form.phone.id_for_label }}" class="form-label">Phone Number</label>
                    {{ form.phone }}
                </div>
            </fieldset>
            <fieldset class="grid grid-cols-2 gap-4">
                <div>
                    {{ form.visit_date.errors }}
                    <label for="{{ form.visit_date.id_for_label }}" class="form-label">When are you planning to visit?</label>
                    {{ form.visit_date }}
                </div>
                <div>
                    {{ form.no.errors }}
                    <label for="{{ form.no.id_for_label }}" class="form-label">How many are you?</label>
                    {{ form.no }}
                </div>
            </fieldset>
            <fieldset class="grid grid-cols-2 gap-4">
                <div>
                    {{ form.group_no.errors }}
                    <label for="{{ form.group_no.id_for_label }}" class="form-label">If a group, How many People are in the group?</label>
                    {{ form.group_no }}
                </div>
                <div>
                    {{ form.tour.errors }}
                    <label for="{{ form.tour.id_for_label }}" class="form-label">Which Tour or Visit are you intrested in?</label>
                    {{ form.tour }}
                </div>
            </fieldset>
            <fieldset class="grid grid-cols-2 gap-4">
                <div>
                    {{ form.contact_choice.errors }}
                    <label for="{{ form.contact_choice.id_for_label }}" class="form-label">What's the best way to contact you?</label>
                    <fieldset>
                        {{ form.contact_choice }}
                    </fieldset>
                </div>
                <div>
                    {{ form.time_choice.errors }}
                    <label for="{{ form.time_choice.id_for_label }}" class="form-label">If phone what is the best time to call you?</label>
                    <fieldset>
                        {{ form.time_choice }}
                    </fieldset>
                </div>
            </fieldset>
            <div>
                {{ form.more_info.errors }}
                <label for="{{ form.more_info.id_for_label }}" class="form-label">Anything Else we should know</label>
                {{ form.more_info }}
            </div>
            <button type="submit" class="hover:bg-primary-950 bg-primary-900 w-fit text-white btn">
                Submit Booking
            </button>
        </form>
    </div>
</section>
{% endblock content %}

contacts/templates/contacts/car-hire.html
{% extends 'base.html' %}
{% load static %}
{% load tailwind_filters %}

{% block title %}Hire a car from Kaizen Safaris{% endblock %}

{% block content %}
<section id="banner" class=" h-[100vh] overflow-hidden shadow-2xl">
    <div class="relative h-full">
        <img class="w-full h-full object-cover" src="{% static 'img/car.webp' %}">
        <div class="cover z-10 absolute top-0 left-0 bottom-0 w-full bg-black bg-opacity-40">
            <!-- <div id="hero-space"></div> -->
            <div class="content-center grid justify-center h-full relative">
                <h1 class="shadowed text-6xl text-white uppercase font-bold text-center h-fit">Cars For Hire</h1>
                <button id="next-section-btn" class="btn bg-white mt-3">
                    <a class="cursor-pointer"> <i class="fas fa-arrow-down mr-4 font-black"></i> Hire cars from us</a>
                </button>
            </div>
        </div>
    </div>
</section>
<div class="hidden">
    <div id="next-section">
        <section class="py-16" id="next">
            <div class="container">
                <p class="mx-auto max-w-2xl text-xl">
                    Welcome to the Kaizen Safaris car shop! Cars are your ticket to a quick weekend or week away with family and friends to relax or enjoy all that the journey has to offer.
                </p>
            </div>
        </section>
        <main class="my-16">
            <div class="container">
                <h2 class="head-1">Fill the form below to hire a car</h2>
            <!-- {{ form|crispy }} -->
            <form method="post" class="booking-form grid gap-4 text-xl">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {{ form.management_form }}
                <fieldset class="grid grid-cols-2 gap-4">
                    <div>
                        {{ form.first_name.errors }}
                        <label for="{{ form.first_name.id_for_label }}" class="form-label">First Name</label>
                        {{ form.first_name }}
                    </div>
                    <div>
                        {{ form.last_name.errors }}
                        <label for="{{ form.last_name.id_for_label }}" class="form-label">Last Name</label>
                        {{ form.last_name }}
                    </div>
                </fieldset>
                <fieldset class="grid grid-cols-2 gap-4">
                    <div>
                        {{ form.email.errors }}
                        <label for="{{ form.email.id_for_label }}" class="form-label">Email</label>
                        {{ form.email }}
                    </div>
                    <div>
                        {{ form.phone.errors }}
                        <label for="{{ form.phone.id_for_label }}" class="form-label">Phone Number</label>
                        {{ form.phone }}
                    </div>
                </fieldset>
                <fieldset class="grid grid-cols-1 gap-4">
                    <div>
                        {{ form.vehicle.errors }}
                        <label for="{{ form.vehicle.id_for_label }}" class="form-label">{{ form.vehicle.label }}</label>
                        {{ form.vehicle }}
                    </div>
                </fieldset>
                <fieldset class="grid grid-cols-2 gap-4">
                    <div>
                        {{ form.contact_choice.errors }}
                        <label for="{{ form.contact_choice.id_for_label }}" class="form-label">What's the best way to contact you?</label>
                        <fieldset>
                            {{ form.contact_choice }}
                        </fieldset>
                    </div>
                    <div>
                        {{ form.time_choice.errors }}
                        <label for="{{ form.time_choice.id_for_label }}" class="form-label">If phone what is the best time to call you?</label>
                        <fieldset>
                            {{ form.time_choice }}
                        </fieldset>
                    </div>
                </fieldset>
                <div>
                    {{ form.more_info.errors }}
                    <label for="{{ form.more_info.id_for_label }}" class="form-label">Anything Else we should know</label>
                    {{ form.more_info }}
                </div>
                <button type="submit" class="text-white bg-primary-900 btn">
                    Hire now
                </button>
            </form>
            </div>
        </main>
    </div>
</div>
{% endblock content %}


{% block styles %}
    <style>
        .card img{
            aspect-ratio: 4 / 3;
        }
    </style>
{% endblock styles %}
    

contacts/templates/contacts/contactpage.html
{% extends 'base.html' %}
{% load static %}



{% block styles %}
<style>
    #banner{
        background-image: url("{% static 'temp/bg/brooke-cagle-g1Kr4Ozfoac-unsplash.jpg' %}");
    }
    input, select, textarea{
        border-color: var(--bs-altlight) !important;
    }
</style>
{% endblock styles %}

{% block title %}
Contact Us
{% endblock title %}

{% block content %}
<section id="contact">
    <div class="container py-5 my-5">
        <div class="row">
            <div class="col-12 col-md-6 col-lg-8 d-flex flex-column fade-in">
                <h2 class="display-4 cursive my-3">Write to us</h2>
                <form method="post" class="h-100 d-flex flex-column bg-white p-4" id="send-mail-form">
                    <div id="token">{% csrf_token %}</div>
                        <div class="row g-1 my-3">
                            <div class="form-floating col-12 col-lg-6">
                                <input name="name" type="text" class="form-control" id="name" required placeholder="John Doe">
                                <label for="name">Name</label>
                            </div>
                            <div class="form-floating col-12 col-lg-6">
                                <input name="phone" type="phone" class="form-control" id="phone" required placeholder="+256..., 07...">
                                <label for="phone">Phone Number</label>
                            </div>
                        </div>
                        <div class="my-3">
                            <div class="form-floating">
                                <input name="email" type="email" class="form-control" id="email" required placeholder="johndoe@outlook.com">
                                <label for="email">Email</label>
                            </div>
                        </div>
                        <div class="my-3 row g-1">
                            <div class="form-floating col-12 col-lg-6 col-xl-4">
                                <select name="session" type="text" class="form-control" id="session" required>
                                        <option value=""><i class="fas fa-carret-down"></i> Select a session</option>
                                    <option value="event">Event</option>
                                    <option value="studio">Studio</option>
                                    <option value="outdoors">Outdoors</option>
                                </select>
                                <!-- <label for="session">Session Type</label> -->
                            </div>
                            <div class="form-floating col-12 col-lg-6 col-xl-4">
                                <input name="date" type="date" class="form-control" id="date" required placeholder="12-04-22">
                                <label for="date">Date</label>
                            </div>
                            <div class="form-floating col-12 col-lg-12 col-xl-4">
                                <input name="eventName" type="eventName" class="form-control" id="eventName" required placeholder="Wedding, Birthday">
                                <label for="eventName">event name</label>
                            </div>
                        </div>
                        <div class="my-3 h-100">
                            <div class="form-floating h-100">
                                <textarea name="moreInfo" class="form-control h-100" id="moreInfo" required placeholder="I want ..." rows="15"></textarea>
                                <label for="moreInfo">More details or information</label>
                                <!-- <label for="moreInfo">Tell us more about your expectations, desired shots etc</label> -->
                            </div>
                        </div>
                        <div class="my-3">
                            <button type="submit" class="btn btn-secondary text-white px-3 fs-5"><i class="bi bi-send-fill me-2"></i>Send</button>
                        </div>
                </form>
            </div>
            <div class="col-12 col-md-6 col-lg-4 fade-in">
                <h2 class="display-4 cursive my-3">Contact us</h2>
                <div class="py-2">
                    <div class="d-flex my-3 bg-white p-4"><i
                        class="bi bi-geo-alt me-3 text-primary"></i><span>Makerere-Kikoni
                        road,
                        Princess Complex, Kasubi room S5</span></div>
                <div class="d-flex my-3 bg-white p-4"><i
                        class="bi bi-clock me-3 text-primary"></i><span>9:00 to 18:00</span></div>
                <div class="d-flex my-3 bg-white p-4"><i
                        class="bi bi-telephone me-3 text-primary"></i><span>+256
                        704360041</span>
                </div>
                <div class="d-flex my-3 bg-white p-4"><i
                        class="bi bi-envelope me-3 text-primary"></i><span>jdrachshots@gmail.com</span></div>
                <div class="d-flex my-3 bg-white p-4"><i
                        class="bi bi-people me-3 text-primary"></i><span>@drach_concepts</span></div>
                <div class="d-flex my-3 bg-white p-4"><i
                        class="bi bi-globe me-3 text-primary"></i><span>www.drachconcepts.com</span></div>
                </div>
            </div>
        </div>
    </div>
</section>
<div id="mailurl" class="d-none">{% url 'contacts:sendmail' %}</div>
{% endblock content %}

{% block scripts %}
<script src="{% static 'js/email.js' %}"></script>
{% endblock scripts %}
    

contacts/templates/contacts/success.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Successfully processed{% endblock %}

{% block content %}
<section class=" h-screen grid place-content-center">
    <div class="text-center py-40">
        <h1 class=" text-6xl font-black text-primary-800">Success <i class="fas fa-check text-lime-500"></i></h1>
        <p class="text-xl my-4">
            We will get back to you shortly
        </p>
        <form>
            <button type="submit" class="btn bg-primary-800 text-white py-2 px-6" formaction="{% url 'main:home-view' %}">
                <i class="fas fa-home mr-4"></i>Back to home
            </button>
        </form>
    </div>
</section>
{% endblock %}
    