api/urls.py
from django.urls import path

from api.views import apiDestinations, apiOverview, days

app_name = 'api'

urlpatterns = [
    path('', apiOverview, name='overview'),
    path('destinations/<str:pk>', apiDestinations, name='destinations'),
    path('days/<str:pk>', days, name='days'),
]

contacts/urls.py
from django.urls import path

from contacts.views import BookingView, CarHireView, SuccessView, TentHireView, sendMail
app_name = 'contacts'

urlpatterns = [
    path('sendmail/', sendMail, name='send_mail'),
    path('booking/', BookingView.as_view(), name='book_now'),
    path('booking/success/', SuccessView.as_view(), name='success'),
    path('forms/tents/', TentHireView.as_view(), name='tent-hire'),
    path('forms/cars/', CarHireView.as_view(), name='car-hire'),
]

kaizen/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf.urls import handler500

handler500 = 'main.views.server_error500'
handler404 = 'main.views.error404View'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls", namespace='main')),
    path('destinations/', include("destinations.urls", namespace='destinations')),
    path('api/', include("api.urls", namespace='api')),
    path('contact/', include("contacts.urls", namespace='contacts')),
]

# handling the 404 error


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.views import HomeView, HoneymoonView, bookingView, equipmentView, galleryView

app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name='home-view'),
    path('equipment/', equipmentView, name='equipment-view'),
    path('gallery/', galleryView, name='gallery-view'),
    path('booking/', bookingView, name='booking-view'),
    path('spots/', HoneymoonView.as_view(), name='honeymoon-list'),
    path('spots/<int:pk>/', HoneymoonView.as_view(), name='honeymoon-detail'),
]

templates/components/footer.html
{% load static %}

<footer class="bg-primary-950 pt-12 pb-8 px-2 shadow-2xl">
    <div class="container text-white">
        <h2 class="hidden">Footer</h2>
        <div class="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
            <figure class="hidden sm:block">
                <img src="{% static 'img/logo-white.webp' %}" alt="logo" class=" scale-90">
            </figure>
            <div>
                <h3 class=" text-2xl font-semibold mb-4">Locate Us</h3>
                <ol class="list-none grid gap-2">
                    <li><i class="fas fa-building w-4 mr-4"></i>Mukasa Towers, Ground Floor</li>
                    <li><i class="fas fa-road w-4 mr-4"></i>Seeta – Namilyango Road</li>
                    <li><i class="fas fa-box w-4 mr-4"></i>P O Box 8437, Mukono, Uganda</li>
                    <li><i class="fas fa-envelope w-4 mr-4"></i>info@kaizensafaris.com</li>
                    <li><i class="fas fa-phone w-4 mr-4"></i>Office: (+256) 393 243 933</li>
                    <li><i class="fab fa-whatsapp w-4 mr-4"></i>Whatsapp:(+256) 755 312 238</li>
                </ol>
            </div>
            <aside class="mt-8 lg:mt-0">
                <h3 class="text-2xl font-semibold mb-4">Popular Links</h3>
                <ol class="list-none grid gap-2">
                    <li>~<a target="_blank" href="https://www.tourism.go.ug/">Ministry of Tourism</a></li>
                    <li>~<a target="_blank" href="https://www.gou.go.ug/ministry/ministry-tourism-wildlife-and-antiquities">Wildlife and Antiquities</a></li>
                    <li>~<a target="_blank" href="https://ugandawildlife.org/">Uganda Wildlife Authority</a></li>
                    <li>~<a target="_blank" href="https://www.gorilla-permits.com/">Gorilla Permits and Licenses</a></li>
                    <li>~<a target="_blank" href="https://visas.immigration.go.ug/">Travel e-Visa</a></li>
                    <li>~<a target="_blank" href="https://utb.go.ug/">Uganda Tourism Board</a></li>
                </ol>
            </aside>
            <div class="mt-8 lg:mt-0">
                <!-- <h3 class="text-2xl font-semibold mb-4">Get in Touch</h3> -->
                <form class="grid gap-2" x-data="main" @submit.prevent="sendMail()">
                    <div id="token">{% csrf_token %}</div>
                    <input x-model="mail.name" type="text" placeholder="Your Name" name="your_name"
                        class="py-1 px-2 w-full rounded-sm text-white placeholder:text-primary-800 bg-primary-950 border-l-2 hover:border-l-8 border-primary-900 border-b focus-within:outline-none focus-within:bg-primary-900 transition-all">
                    <input x-model="mail.email" type="email" placeholder="Your email" name="your_email"
                        class="py-1 px-2 w-full rounded-sm text-white placeholder:text-primary-800 bg-primary-950 border-l-2 hover:border-l-8 border-primary-900 border-b focus-within:outline-none focus-within:bg-primary-900 transition-all">
                    <textarea x-model="mail.message" name="your_message" cols="30" rows="4" placeholder="How can we help you?"
                        class="py-1 px-2 w-full rounded-sm text-white placeholder:text-primary-800 bg-primary-950 border-l-2 hover:border-l-8 border-primary-900 border-b focus-within:outline-none focus-within:bg-primary-900 transition-all"></textarea>
                    <button type="submit"
                        class="hover:bg-white outline-2 outline outline-white w-fit text-white hover:text-black btn"
                        >Send a message</button> <span class="" x-text="status"></span>
                </form>
            </div>
        </div>
        <p class="text-center mt-4 text-primary-100">
            © Copyright 2025 - Kaizen Safaris - All Rights Reserved.
        </p>
        <ul class=" list-none flex gap-4 justify-center text-xl">
            <li>
                <a target="_blank" href="https://www.facebook.com/kaizensafaris" class=""><i class="fab fa-facebook"></i></a>
            </li>
            <li>
                <a target="_blank" href="https://x.com/KaizenSafaris" class="">
                    <i class="fab fa-twitter"></i>
                    <i class="fab fa-x"></i>
                </a>
            </li>
            <li>
                <a target="_blank" href="https://www.instagram.com/kaizensafarisug/" class=""><i class="fab fa-instagram"></i></a>
            </li>
            <li><a target="_blank" href="https://wa.me/256755312238" class=""><i class="fab fa-whatsapp"></i></a></li>
            <li>
                <a target="_blank" href="mailto:kaizensafaris@gmail.com" class=""><i class="fas fa-envelope"></i></a>
            </li>
            <li>
                <a target="_blank" href="https://www.linkedin.com/in/kaizen-safaris-8a7845199/" class=""><i class="fab fa-linkedin"></i></a>
            </li>
            <li>
                <a target="_blank" href="https://www.youtube.com/@kaizensafaris" class=""><i class="fab fa-youtube"></i></a>
            </li>
        </ul>
    </div>
</footer>

templates/components/header.html
{% load static %}


<header class="fixed w-full z-50" id="navbar-sticky">
    <div class="container">
        <nav class="flex justify-between py-4">
            <div class="nav-brand">
                <a href="/" class="">
                    <img src="{% static 'img/logo.webp' %}" alt="Kaizen Safaris" class="md:h-24 h-16">
                </a>
            </div>
            <div class="menu grid content-center">
                <ol class="nav-list list-none hidden md:flex gap-2 lg:gap-4 bg-[rgba(0,0,0,0.3)] px-8 py-2">
                    <li class="grid content-center"><a href="/" class="nav-link link">Home</a></li>
                    <li class="grid content-center relative dropdown">
                        <a class="nav-link link cursor-default">Destinations</a>
                        <div class="dropdown-content absolute bg-white hidden py-4 rounded w-max" x-data='main'>
                            <template x-for="d in destinations">
                                <a :href="`/destinations/${d.id}/`" class="link hover:bg-slate-100  px-3 py-2 whitespace-nowrap" x-text="d.name">
                                    {{ destination.name }}
                                </a>
                            </template>
                        </div>
                    </li>
                    <li class="grid content-center relative dropdown">
                        <a class="nav-link link cursor-default">Services</a>
                        <div class="dropdown-content absolute bg-white hidden py-4 rounded w-max">
                            <a href="{% url 'contacts:car-hire' %}" class="link hover:bg-slate-100 w-full px-3 py-2">
                                Car Hire
                            </a>
                            <a href="{% url 'contacts:tent-hire' %}" class="link hover:bg-slate-100  px-3 py-2 whitespace-nowrap">
                                Camping Equipment
                            </a>
                        </div>
                    </li>
                    <li class="grid content-center"><a href="{% url 'main:gallery-view' %}"
                            class="nav-link link">Gallery</a></li>
                    <li class="grid content-center"><a href="{% url 'contacts:book_now' %}"
                            class="nav-link link">Book Now</a></li>
                </ol>
                <span class="grid content-center md:hidden text-2xl p-2 text-white">
                    <i class="fas fa-bars" id="menu-btn"></i>
                </span>
            </div>
        </nav>
    </div>
</header>
<div class="fixed smmenu -top-full left-0 bg-white z-40 h-full w-full block md:hidden">
    <div class="h-full w-full grid place-content-center inner">
        <ul class="text-black list-none">
            <li class="md:grid content-center relative dropdown bg-slate-50 my-4 text-center text-xl rounded-2xl px-4"
                x-data="
                        {
                            destinations: null,
                            getDestinations() {
                                fetch('{% url 'api:destinations' 'all' %}')
                                    .then((response) => response.json())
                                    .then((json) => this.destinations = json);
                            }
                        }
                        " x-init="getDestinations()">
                <a class=" cursor-default">Countries <i class="fas fa-caret-down"></i></a>
                <div class="dropdown-content absolute shadow-lg bg-white hidden py-4 rounded w-full">
                    <template x-for="destination in destinations">
                        <a @click="window.location.href = `/destinations/${destination.id}`" x-text="destination.name"
                            class="my-1 text-center hover:bg-slate-400 w-full px-3 cursor-pointer"></a>
                    </template>
                </div>
            </li>
            <li class="md:grid content-center bg-slate-50 my-4 text-center text-xl rounded-2xl px-4"><a
                    href="{% url 'contacts:car-hire' %}" class="">Car hire</a></li>
            <li class="md:grid content-center bg-slate-50 my-4 text-center text-xl rounded-2xl px-4"><a
                    href="{% url 'contacts:tent-hire' %}" class="">Camping
                    Equipment</a></li>
            <li class="md:grid content-center bg-slate-50 my-4 text-center text-xl rounded-2xl px-4"><a
                    href="{% url 'main:gallery-view' %}" class="">Gallery</a></li>
            <div class="close-nav text-4xl text-center mt-8 "><i class="fas fa-close"></i></div>
        </ul>
    </div>
</div>


{% block styles %}
<style>
    .dropdown:hover .dropdown-content {
        display: grid;
        top: 100%;
    }
</style>
{% endblock styles %}